{{- if .Values.persistence.logs.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "honua.fullname" . }}-logs
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "honua.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.persistence.logs.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.logs.size }}
  {{- if .Values.persistence.logs.storageClass }}
  storageClassName: {{ .Values.persistence.logs.storageClass }}
  {{- else if .Values.global.storageClass }}
  storageClassName: {{ .Values.global.storageClass }}
  {{- end }}
{{- end }}
---
{{- if .Values.persistence.buildWorkspace.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "honua.fullname" . }}-build-workspace
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "honua.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.persistence.buildWorkspace.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.buildWorkspace.size }}
  {{- if .Values.persistence.buildWorkspace.storageClass }}
  storageClassName: {{ .Values.persistence.buildWorkspace.storageClass }}
  {{- else if .Values.global.storageClass }}
  storageClassName: {{ .Values.global.storageClass }}
  {{- end }}
{{- end }}
---
{{- if .Values.persistence.buildCache.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "honua.fullname" . }}-build-cache
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "honua.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.persistence.buildCache.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.buildCache.size }}
  {{- if .Values.persistence.buildCache.storageClass }}
  storageClassName: {{ .Values.persistence.buildCache.storageClass }}
  {{- else if .Values.global.storageClass }}
  storageClassName: {{ .Values.global.storageClass }}
  {{- end }}
{{- end }}
