{{- if .Values.api.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "honua.fullname" . }}-api
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "honua.api.labels" . | nindent 4 }}
  {{- with .Values.api.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.api.service.type }}
  selector:
    {{- include "honua.api.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.api.service.port }}
      targetPort: http
      protocol: TCP
    - name: metrics
      port: {{ .Values.api.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
  sessionAffinity: ClientIP
{{- end }}
---
{{- if .Values.intake.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "honua.fullname" . }}-intake
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "honua.intake.labels" . | nindent 4 }}
  {{- with .Values.intake.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.intake.service.type }}
  selector:
    {{- include "honua.intake.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.intake.service.port }}
      targetPort: http
      protocol: TCP
    - name: metrics
      port: {{ .Values.intake.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
{{- end }}
