{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "honua.api.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "honua.api.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "honua.intake.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "honua.intake.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "honua.orchestrator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "honua.orchestrator.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
